" Use dracula theme
" @see https://draculatheme.com/vim
packadd! dracula
syntax enable
colorscheme dracula

" Use 4 spaces instead of tabs
" @see https://stackoverflow.com/questions/234564/tab-key-4-spaces-and-auto-indent-after-curly-braces-in-vim
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
